/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import contentVersioning from "@notum-cz/strapi-plugin-content-versioning/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import tagsinput from "strapi-plugin-tagsinput/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    ckeditor: ckeditor,
    "content-versioning": contentVersioning,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "config-sync": configSync,
    tagsinput: tagsinput,
  },
});
